DATA:
  DATA_NAME: 'THUMOS'
  DATA_INFO: '/home/dx/data/houlin/Memory-and-Anticipation-Transformer/data/data_info.json'
  DATA_ROOT: '/home/dx/data/houlin/Memory-and-Anticipation-Transformer/data/thumos14'
#  DATA_INFO: '/data1/houlin/MATData/data/data_info.json'
#  DATA_ROOT: '/data1/houlin/MATData/data/thumos14'mamba_ssm
INPUT:
#  MODALITY: 'visual'
  MODALITY: 'twostream'
  VISUAL_FEATURE: 'rgb_kinetics_resnet50'
  MOTION_FEATURE: 'flow_kinetics_bninception'
MODEL:
  MODEL_NAME: 'LSTR'
  FEATURE_HEAD:
    LINEAR_ENABLED: True
    LINEAR_OUT_FEATURES: 1024
  LSTR:
    NUM_HEADS: 4
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.
    ACTIVATION: 'gelu'
    LONG_MEMORY_SECONDS: 256
    LONG_MEMORY_SAMPLE_RATE: 4
    WORK_MEMORY_SECONDS: 8
    WORK_MEMORY_SAMPLE_RATE: 1
    FUTURE_SECONDS: 12
    FUTURE_SAMPLE_RATE: 1
    ANTICIPATION_SECONDS: 2
    ANTICIPATION_SAMPLE_RATE: 1
    GROUPS: 8
    CCI_TIMES: 2
    ENC_MODULE: [
      [16, 1, True],[-1, 2, True]
    ]
    DEC_MODULE: [-1, 2, True]
    GEN_MODULE: [32, 2, True]
    FUT_MODULE: [
    [48, 1, True],
    ]
  CRITERIONS: [['MCE', {}]]
DATA_LOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 8
  PIN_MEMORY: True
SOLVER:
  NUM_EPOCHS: 35
  OPTIMIZER: 'Adam'
  BASE_LR: 7e-05
#  BASE_LR: 1e-03
  WEIGHT_DECAY: 5e-05
#  WEIGHT_DECAY: 5e-03
  SCHEDULER:
    SCHEDULER_NAME: 'warmup_cosine'
#    WARMUP_FACTOR: 0.9
    WARMUP_FACTOR: 0.3
    WARMUP_EPOCHS: 10.0
    WARMUP_METHOD: 'linear'

OUTPUT_DIR: /home/dx/data/houlin/RGB_Only_checkpoints/
#OUTPUT_DIR: /data1/houlin/MATData/checkpoints